import { IslamicModule } from '../types';

export const ISLAMIC_MODULES: IslamicModule[] = [
  {
    id: 'how-to-start',
    type: 'guide',
    category: 'manners',
    title: 'How To Learn In Islamic Corner',
    subtitle: 'Small steps, listening, practice, and one simple quiz.',
    emoji: '🌙',
    objective: 'Help children understand how the Islamic Corner works before deeper lessons begin.',
    ageBand: '4-6',
    guidance: [
      'Listen to the dua or tip slowly.',
      'Repeat it with Lumi or a parent.',
      'Practice it in real life when the moment comes.',
      'Finish the quiz to unlock your reward.',
    ],
    tips: [
      'Short lessons are better than long lectures.',
      'Repeat the same dua for a few days until it feels natural.',
      'Parents can practice together after meals or before bed.',
    ],
    rewardXp: 10,
    rewardCoins: 2,
    quiz: [
      {
        id: 'start-1',
        prompt: 'What should you do after listening to a dua?',
        options: [
          { id: 'a', text: 'Repeat it slowly' },
          { id: 'b', text: 'Close the app immediately' },
          { id: 'c', text: 'Ignore it' },
        ],
        correctOptionId: 'a',
        explanation: 'Repeating the dua helps children remember and use it in daily life.',
      },
    ],
  },
  {
    id: 'dua-before-eating',
    type: 'dua',
    category: 'daily_duas',
    title: 'Dua Before Eating',
    subtitle: 'A short dua to say before starting food.',
    emoji: '🍽️',
    objective: 'Teach children to begin meals by remembering Allah.',
    ageBand: '4-6',
    arabic: 'بِسْمِ اللهِ',
    transliteration: 'Bismillah',
    meaning: 'In the name of Allah.',
    whenToUse: 'Say it before eating food or drinking.',
    guidance: [
      'Sit nicely before your meal.',
      'Say the dua before your first bite.',
      'Eat with calm hands and good manners.',
    ],
    tips: [
      'This is one of the easiest daily duas for children to memorize.',
      'Practice it at every meal until it becomes automatic.',
    ],
    rewardXp: 15,
    rewardCoins: 3,
    unlockAfterId: 'how-to-start',
    quiz: [
      {
        id: 'eat-1',
        prompt: 'When do you say Bismillah?',
        options: [
          { id: 'a', text: 'Before eating' },
          { id: 'b', text: 'After sleeping' },
          { id: 'c', text: 'When putting shoes away' },
        ],
        correctOptionId: 'a',
        explanation: 'This dua is said before food or drink.',
      },
      {
        id: 'eat-2',
        prompt: 'What does Bismillah mean?',
        options: [
          { id: 'a', text: 'Good night' },
          { id: 'b', text: 'In the name of Allah' },
          { id: 'c', text: 'Thank you for the food' },
        ],
        correctOptionId: 'b',
        explanation: 'Bismillah means “In the name of Allah.”',
      },
    ],
  },
  {
    id: 'dua-before-sleep',
    type: 'dua',
    category: 'daily_duas',
    title: 'Dua Before Sleep',
    subtitle: 'A bedtime remembrance children can learn with parents.',
    emoji: '🛏️',
    objective: 'Create a peaceful bedtime habit through simple remembrance.',
    ageBand: '4-6',
    arabic: 'بِاسْمِكَ اللّٰهُمَّ أَمُوتُ وَأَحْيَا',
    transliteration: 'Bismika Allahumma amutu wa ahya',
    meaning: 'O Allah, in Your name I die and I live.',
    whenToUse: 'Say it before sleeping at night.',
    guidance: [
      'Get into bed calmly.',
      'Say the dua slowly.',
      'Sleep with a thankful heart.',
    ],
    tips: [
      'Bedtime duas work well when paired with a simple nightly routine.',
      'Keep the wording short for very young children at first.',
    ],
    rewardXp: 18,
    rewardCoins: 3,
    unlockAfterId: 'dua-before-eating',
    quiz: [
      {
        id: 'sleep-1',
        prompt: 'When should this dua be used?',
        options: [
          { id: 'a', text: 'Before sleeping' },
          { id: 'b', text: 'Before going outside' },
          { id: 'c', text: 'Before opening a book' },
        ],
        correctOptionId: 'a',
        explanation: 'This is a bedtime dua.',
      },
    ],
  },
  {
    id: 'wudu-steps',
    type: 'guide',
    category: 'salah_basics',
    title: 'Wudu Step By Step',
    subtitle: 'A child-friendly sequence for learning ablution.',
    emoji: '💧',
    objective: 'Help children remember the basic order of wudu.',
    ageBand: '6-8',
    guidance: [
      'Make the intention to prepare for prayer.',
      'Wash your hands.',
      'Rinse your mouth and nose gently.',
      'Wash your face carefully.',
      'Wash your arms up to the elbows.',
      'Wipe your head and ears.',
      'Wash your feet.',
    ],
    tips: [
      'Children learn this best by watching and copying a parent.',
      'Use one step at a time until the order becomes familiar.',
    ],
    rewardXp: 22,
    rewardCoins: 4,
    unlockAfterId: 'dua-before-sleep',
    quiz: [
      {
        id: 'wudu-1',
        prompt: 'Which one comes first in this lesson?',
        options: [
          { id: 'a', text: 'Wash feet' },
          { id: 'b', text: 'Wash hands' },
          { id: 'c', text: 'Wipe head' },
        ],
        correctOptionId: 'b',
        explanation: 'The simplified sequence here begins with washing the hands.',
      },
      {
        id: 'wudu-2',
        prompt: 'Why do we learn wudu?',
        options: [
          { id: 'a', text: 'To prepare for prayer' },
          { id: 'b', text: 'To unlock a toy' },
          { id: 'c', text: 'To skip bedtime' },
        ],
        correctOptionId: 'a',
        explanation: 'Wudu prepares a Muslim for salah.',
      },
    ],
  },
  {
    id: 'salam-and-kindness',
    type: 'guide',
    category: 'manners',
    title: 'Say Salam And Be Kind',
    subtitle: 'A simple manners lesson for home and everyday life.',
    emoji: '🤝',
    objective: 'Teach children that Islamic learning includes good manners, not only memorization.',
    ageBand: '4-6',
    guidance: [
      'Say salam when meeting family or friends.',
      'Use gentle words.',
      'Share and help where you can.',
      'Respect parents and elders.',
    ],
    tips: [
      'Children remember manners faster when they see them practiced every day.',
      'Praise kind actions right after they happen.',
    ],
    rewardXp: 14,
    rewardCoins: 2,
    unlockAfterId: 'how-to-start',
    quiz: [
      {
        id: 'salam-1',
        prompt: 'What is a good Islamic greeting?',
        options: [
          { id: 'a', text: 'Assalamu Alaikum' },
          { id: 'b', text: 'See you later' },
          { id: 'c', text: 'Maybe tomorrow' },
        ],
        correctOptionId: 'a',
        explanation: 'Assalamu Alaikum is a beautiful Islamic greeting to teach children early.',
      },
    ],
  },
];

export const ISLAMIC_CATEGORY_LABELS: Record<IslamicModule['category'], string> = {
  daily_duas: 'Daily Duas',
  salah_basics: 'Salah Basics',
  manners: 'Islamic Manners',
};

